
import json
import secrets

from flask import (
    current_app,
    jsonify,
    redirect,
    request,
    session,
    url_for,
    flash,
)
from flask_login import current_user, login_required
from google.auth.exceptions import GoogleAuthError

from google_calendar import (
    create_oauth_flow,
    fetch_calendar_events,
    credentials_from_dict,
)

# Use the database and model imports from your existing project.
# Example only; adjust these to match your team's code:
# from models import db, Activity
# or: from model import db, Activity


@app.route("/calendar/connect")
@login_required
def calendar_connect():
    """Start Google Calendar authorization."""
    state = secrets.token_urlsafe(32)
    session["google_oauth_state"] = state

    flow = create_oauth_flow(state=state)

    authorization_url, returned_state = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent",
    )

    # Keep the state generated by our app; Google's returned state
    # should match it.
    if returned_state != state:
        return "OAuth state mismatch", 400

    return redirect(authorization_url)


@app.route("/oauth2callback")
@login_required
def oauth2callback():
    """Handle Google's redirect after the user grants or denies access."""
    if request.args.get("error"):
        session.pop("google_oauth_state", None)
        flash("Google Calendar connection was cancelled or denied.", "warning")
        return redirect(url_for("dashboard"))

    expected_state = session.pop("google_oauth_state", None)
    received_state = request.args.get("state")

    if (
        not expected_state
        or not received_state
        or not secrets.compare_digest(expected_state, received_state)
    ):
        return "Invalid OAuth state. Please try connecting again.", 400

    try:
        flow = create_oauth_flow(state=expected_state)
        flow.fetch_token(authorization_response=request.url)

        # Persist credentials for THIS logged-in user.
        current_user.google_credentials = flow.credentials.to_json()
        db.session.commit()

    except Exception:
        current_app.logger.exception("Google Calendar OAuth failed")
        db.session.rollback()
        flash("Could not connect Google Calendar. Please try again.", "error")
        return redirect(url_for("dashboard"))

    flash("Google Calendar connected successfully!", "success")
    return redirect(url_for("dashboard"))